export const actions = {
  fetchClientes: 'FETCH_CLIENTES',
  fetchClientesError: 'FETCH_CLIENTES_ERROR',
  fetchClientesSuccess: 'FETCH_CLIENTES_SUCCESS',
  fetchClienteId: 'FETCH_CLIENTE_ID',
  fetchClienteIdError: 'FETCH_CLIENTE_ID_ERROR',
  fetchClienteIdSuccess: 'FETCH_CLIENTE_ID_SUCCESS',
  setReload: 'SET_RELOAD',
  setterCliente: 'SETTER_CLIENTE',
  saveCliente: 'SAVE_CLIENTE',
  saveClienteSuccess: 'SAVE_CLIENTE_SUCCESS',
  saveClienteError: 'SAVE_CLIENTE_ERROR',
  deleteCliente: 'DELETE_CLIENTE',
  deleteClienteSuccess: 'DELETE_CLIENTE_SUCCESS',
  deleteClienteError: 'DELETE_CLIENTE_ERROR',
  updateCliente: 'UPDATE_CLIENTE',
  updateClienteSuccess: 'UPDATE_CLIENTE_SUCCESS',
  updateClienteError: 'UPDATE_CLIENTE_ERROR',
};
